name: 'Lambda Pipeline'
description: 'Given a program name, git tag, and directory containing integration tests, this action promotes via parameter store tag updates and tests the program as a Lambda'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key ID'
    required: true
    default: null
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key'
    required: true
    default: null
  AWS_REGION:
    description: 'AWS Lambda and S3 bucket region'
    required: true
    default: null
  PROGRAM_NAME:
    description: 'Program whose binary is being run through the pipeline'
    required: true
    default: null
  NEW_TAG:
    description: 'Tag that represents the version of the binary that is being run through the pipeline'
    required: true
    default: null
  TEST_DIR:
    description: 'Directory containing the integration tests to be executed to verify the new binary runs successfully in a Lambda'
    required: true
    default: null
  TEST_NAME:
    description: 'Optional name of the go test program to be run (e.g. mytest.go)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.AWS_ACCESS_KEY_ID }}
    - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - ${{ inputs.AWS_REGION }}
    - ${{ inputs.PROGRAM_NAME }}
    - ${{ inputs.NEW_TAG }}
    - ${{ inputs.TEST_DIR }}
    - ${{ inputs.TEST_NAME }}
